server:
  port: 8888

spring:
  datasource:
    #url: jdbc:mysql://192.168.35.227:3306/community_board?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/test_project?useSSL=false&allowPublicKeyRetrieval=true
    #username: admin
    username: tester
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

mybatis:
  type-aliases-package: mybatis.communityBoard.entity, mybatis.communityBoard.dto.*
  mapper-locations:  mybatis/mappers/*
